name: manage-azure-policy-7e6d0ce0
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Microsoft_365_Sertifikası_için_ACAT_80307b86-ab81-45ab-bf4f-4e0b93cf3dd5/**'
#      - .github/workflows/manage-azure-policy-7e6d0ce0.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_7e6d0ce0}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Microsoft_365_Sertifikası_için_ACAT_80307b86-ab81-45ab-bf4f-4e0b93cf3dd5/**
